version: '2.32.4'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5434:5432

  rabbitmq:
    image: rabbitmq:3.9
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5673:5672